### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by elnappo** [elnappo/project-novis#21]
* Logo
* Favicon
* iOS Icon

**Comment by mirzazulfan** [comment]
Hi @elnappo , I've designed a logo for your project, what do you think? if you need to change please let me know. Regard.
![project novis](https://user-images.githubusercontent.com/36124339/54813627-8a588680-4cc0-11e9-8bf3-622fb994e526.png)

**Comment by elnappo** [comment]
Wow! Awesome! Thank you very much!

I like the first proposal more. Color looks great!
I would like to use the second icon (without color shift) as favicon and the third (blue) for iOS. Would it be hard to create a second version of the logo (icon + text) in blue? For use in our readme and in the documentation. With white or transparent background, whatever makes more sense?

Do you need anything further? Glad to help you out! I further added a contributors section and would like to add you there if you don't mind.

Again, thank you! :)

**Comment by mirzazulfan** [comment]
Hi @elnappo ..Thanks for your response, I'm glad you liked it. Do you mean like this?
![version 1](https://user-images.githubusercontent.com/36124339/54908069-a0ad4f00-4f19-11e9-9e48-4df942390f35.png)

**Comment by elnappo** [comment]
Thank you, that was quick! ;)
Yes, that's perfect :)
If I understand it correctly the logo with color shift should be used on the left side in the navigation bar on www.project-novis.org? Shouldn't the right blue in the color shift match the blue tone on www.project-novis.org?

Do you have any preferences regarding the license of the logo?

**Comment by mirzazulfan** [comment]
Hi again @elnappo . I've fixed it the color according to the color of the website. You can download all files here https://drive.google.com/drive/folders/1-WSczpVchTmzAvh-UMPUN3JFtDhP-Ci0 ,, also I created a pr #31.

If you need to change dont hesitate to cantact me. Best Regard.

#### Licence
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
</center>

**Comment by elnappo** [comment]
Awesome! Thanks! :) I will integrate it in the following days!

**Comment by elnappo** [comment]
@mirzazulfan I you don't mind asking, @ThomasWaldmann and I are maintainer of a completely free and open source [dyndns](https://en.wikipedia.org/wiki/Dynamic_DNS) provider. There is also an issue regarding a logo https://github.com/nsupdate-info/nsupdate.info/issues/78 if you want to create another one ;)

**Comment by ThomasWaldmann** [comment]
That would be very cool! :)

**Comment by mirzazulfan** [comment]
I'll take a look and try to design it if I can :) Thank you!

**Comment by elnappo** [comment]
Took a litte bit longer than expected but where online now! :)
